### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by TacoAnime69** [TacoAnime69/nh-pdf-downloader#7]
# Memory Issue
ID Used: `330293`
Error: 
```
Traceback (most recent call last):
  File "__main__.py", line 277, in <module>
    get_command(output_folder, all_temp, history_log)
  File "__main__.py", line 263, in get_command
    process_queue(num_input, output_folder, temp_folder, log)
  File "__main__.py", line 233, in process_queue
    pdf_handler.save_to_pdf(images, path_handler.final_path)
  File "__main__.py", line 67, in save_to_pdf
    converted.append(img.convert('RGBA').convert('RGB'))
  File "C:\Users\oa_jo\AppData\Roaming\Python\Python38\site-packages\PIL\Image.py", line 1024, in convert
    im = self.im.convert(mode, dither)
MemoryError
```

**Comment by TacoAnime69** [comment]
Just realized I put in the number twice. Still shouldn't give this error.
